-- =============================================================================
-- LLM Wiki v2 Schema — 投资研究专用
-- =============================================================================
-- 设计文档：doc/architecture.md
--
-- 执行方式（首次部署或重建）：
--   psql -h <host> -U ae_root -d ae_wiki -f init-v2.sql
--
-- 幂等性：所有 CREATE 语句均带 IF NOT EXISTS 或等价；可重复执行。
--
-- 设计原则：
--   1. 万物皆 page（gbrain 思想）
--   2. 投资强查询字段直接进 pages 列
--   3. Facts / Theses / Signals 投资专属表
--   4. 不使用外键约束（应用层控制完整性）
--   5. 不支持物理删除（append-only + soft archive via deleted=1 / status=archived）
--   6. Provenance 一等公民
--   7. 所有表统一审计字段（extend / create_by / update_by / create_time / update_time / deleted）
-- =============================================================================


-- =============================================================================
-- §0. 扩展
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector：向量类型 + HNSW
CREATE EXTENSION IF NOT EXISTS pg_trgm;      -- 三元组索引：模糊搜索
CREATE EXTENSION IF NOT EXISTS pgcrypto;     -- gen_random_uuid() 等


-- =============================================================================
-- §1. 注意事项
-- =============================================================================
-- update_time 字段不在 DB 层自动维护，由应用层在 UPDATE 时显式 SET update_time = NOW()
-- 所有 INSERT/UPDATE 必须由应用层填 create_by / update_by


-- =============================================================================
-- §2. 表定义（15 张）
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2.1 sources — 多租户分区
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sources (
  id           TEXT PRIMARY KEY,                               -- 'default' | 'sandbox' | ...
  name         TEXT        NOT NULL,
  description  TEXT,
  config       JSONB       NOT NULL DEFAULT '{}'::jsonb,
  -- 标准审计字段
  extend       JSONB,
  create_by    VARCHAR(64) NOT NULL DEFAULT '',
  update_by    VARCHAR(64) NOT NULL DEFAULT '',
  create_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted      SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.2 pages — 核心表（万物皆 page）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pages (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id    TEXT        NOT NULL DEFAULT 'default',
  slug         TEXT        NOT NULL,                            -- 'companies/NVIDIA' / 'sources/arete-NOW-260316'
  type         TEXT        NOT NULL,                            -- 'company' | 'person' | 'industry' | 'concept' | 'source' | 'thesis' | 'output'
  title        TEXT        NOT NULL,

  -- 内容
  content      TEXT        NOT NULL DEFAULT '',                 -- 主体 markdown narrative
  tokens_zh    TEXT,                                            -- 应用层 jieba 切完的空格分隔串（喂 tsv）
  timeline     TEXT        NOT NULL DEFAULT '',                 -- markdown 时间线段落（人读版本）
  frontmatter  JSONB       NOT NULL DEFAULT '{}',
  content_hash TEXT,                                            -- SHA-256(content) 变更检测

  -- 投资强查询字段（type='company' 时填）
  ticker       TEXT,                                            -- 'NOW-US' / '600519.SH'
  exchange     TEXT,
  aliases      TEXT[],
  sector       TEXT,
  sub_sector   TEXT,
  country      TEXT,

  -- 检索
  embedding    vector(1536),
  tsv          tsvector,

  -- 组织 / 权限（继承自 raw_files.org_code 或人工创建时填）
  org_code     TEXT,                                            -- 例 'JG1000'，后续作为多租户/权限边界

  -- 状态
  status       TEXT        NOT NULL DEFAULT 'active',           -- 'active' | 'draft' | 'archived'
  confidence   TEXT,                                            -- 'high' | 'medium' | 'low'

  -- 标准审计字段
  extend       JSONB,
  create_by    VARCHAR(64) NOT NULL DEFAULT '',
  update_by    VARCHAR(64) NOT NULL DEFAULT '',
  create_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted      SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.3 content_chunks — 分段 embedding
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS content_chunks (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id      BIGINT      NOT NULL,
  chunk_index  INTEGER     NOT NULL,
  chunk_text   TEXT        NOT NULL,
  chunk_type   TEXT        NOT NULL DEFAULT 'text',             -- 'text' | 'list' | 'table' | 'chart' | 'compiled_truth'
  page_idx     INTEGER,                                         -- mineru 提供的原文档页码
  embedding    vector(1536),
  model        TEXT        NOT NULL DEFAULT 'text-embedding-3-large',
  token_count  INTEGER,
  embedded_at  TIMESTAMPTZ,
  -- 标准审计字段
  extend       JSONB,
  create_by    VARCHAR(64) NOT NULL DEFAULT '',
  update_by    VARCHAR(64) NOT NULL DEFAULT '',
  create_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted      SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.4 links — 类型化边 + provenance
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS links (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_page_id    BIGINT      NOT NULL,
  to_page_id      BIGINT      NOT NULL,
  link_type       TEXT        NOT NULL DEFAULT 'mention',       -- 'mention' | 'covers' | 'competes_with' | 'invests_in' | ...
  context         TEXT        NOT NULL DEFAULT '',
  link_source     TEXT,                                         -- 'markdown' | 'frontmatter' | 'manual' | 'extracted'
  origin_page_id  BIGINT,
  origin_field    TEXT,
  weight          NUMERIC     NOT NULL DEFAULT 1.0,
  -- 标准审计字段
  extend          JSONB,
  create_by       VARCHAR(64) NOT NULL DEFAULT '',
  update_by       VARCHAR(64) NOT NULL DEFAULT '',
  create_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted         SMALLINT    NOT NULL DEFAULT 0,

  CONSTRAINT links_type_check CHECK (link_source IS NULL OR link_source IN ('markdown', 'frontmatter', 'manual', 'extracted'))
);


-- -----------------------------------------------------------------------------
-- 2.5 tags
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id     BIGINT      NOT NULL,
  tag         TEXT        NOT NULL,
  -- 标准审计字段
  extend      JSONB,
  create_by   VARCHAR(64) NOT NULL DEFAULT '',
  update_by   VARCHAR(64) NOT NULL DEFAULT '',
  create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted     SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.6 facts — 时间序列结构化数值（投资专属，最重要）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS facts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_page_id  BIGINT      NOT NULL,                         -- subject: 关于哪个公司/行业
  metric          TEXT        NOT NULL,                         -- 'revenue' | 'ebit' | 'eps_non_gaap' | 'target_price' | ...
  period          TEXT,                                         -- 'FY2027E' | '1Q26A' | 'current'
  period_start    DATE,
  period_end      DATE,
  value_numeric   NUMERIC,
  value_text      TEXT,
  unit            TEXT,                                         -- 'usd_m' | 'pct' | 'x' | ...
  source_page_id  BIGINT,                                       -- citation: 哪份 source 提供
  confidence      NUMERIC     NOT NULL DEFAULT 1.0,
  valid_from      DATE        NOT NULL,
  valid_to        DATE,                                         -- NULL = 当前 latest
  metadata        JSONB                DEFAULT '{}',            -- {"is_consensus": true, "broker": "..."}
  ingested_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- 标准审计字段
  extend          JSONB,
  create_by       VARCHAR(64) NOT NULL DEFAULT '',
  update_by       VARCHAR(64) NOT NULL DEFAULT '',
  create_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted         SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.7 theses — 投资论点状态机（投资专属）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS theses (
  page_id               BIGINT PRIMARY KEY,                     -- 1:1 扩展 pages
  target_page_id        BIGINT      NOT NULL,                   -- 标的（公司/行业 page）
  direction             TEXT        NOT NULL,                   -- 'long' | 'short' | 'pair' | 'neutral'
  conviction            TEXT,                                   -- 'high' | 'medium' | 'low'
  status                TEXT        NOT NULL,                   -- 'active' | 'monitoring' | 'closed' | 'invalidated'
  date_opened           DATE,
  date_closed           DATE,
  price_at_open         NUMERIC,
  price_at_close        NUMERIC,
  catalysts             JSONB       NOT NULL DEFAULT '[]',      -- [{date, event, expected_impact}]
  validation_conditions JSONB       NOT NULL DEFAULT '[]',      -- [{condition, status, last_checked}]
  pm_owner              TEXT,
  -- 标准审计字段
  extend                JSONB,
  create_by             VARCHAR(64) NOT NULL DEFAULT '',
  update_by             VARCHAR(64) NOT NULL DEFAULT '',
  create_time           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted               SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.8 signals — 自动事件流（投资专属）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS signals (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_type     TEXT        NOT NULL,                         -- 'consensus_drift' | 'thesis_validation' | 'earnings_surprise' | ...
  entity_page_id  BIGINT,
  thesis_page_id  BIGINT,
  source_page_id  BIGINT,
  severity        TEXT        NOT NULL DEFAULT 'info',          -- 'critical' | 'warning' | 'info'
  title           TEXT        NOT NULL,
  detail          TEXT,
  data            JSONB,
  resolved        BOOLEAN     NOT NULL DEFAULT FALSE,
  detected_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at     TIMESTAMPTZ,
  -- 标准审计字段
  extend          JSONB,
  create_by       VARCHAR(64) NOT NULL DEFAULT '',
  update_by       VARCHAR(64) NOT NULL DEFAULT '',
  create_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted         SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.9 timeline_entries — 结构化事件流
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS timeline_entries (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_page_id  BIGINT,
  source_page_id  BIGINT,
  event_date      DATE        NOT NULL,
  event_type      TEXT        NOT NULL,                         -- 'earnings' | 'guidance' | 'rating_change' | ...
  summary         TEXT        NOT NULL,
  detail          TEXT,
  metadata        JSONB                DEFAULT '{}',
  -- 标准审计字段
  extend          JSONB,
  create_by       VARCHAR(64) NOT NULL DEFAULT '',
  update_by       VARCHAR(64) NOT NULL DEFAULT '',
  create_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted         SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.10 raw_files — 原始文件登记
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_files (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id         TEXT        NOT NULL DEFAULT 'default',
  markdown_url      TEXT        NOT NULL,                       -- 上游 parsedMarkdownS3 直链；ingest 按需 fetch（不再落盘）
  research_id       TEXT,                                       -- 上游 ResearchReportRecord.researchId
  research_type     TEXT,                                       -- 'meeting_minutes' | 'arete' | 'twitter' | ...
  org_code          TEXT,                                       -- 上游 orgCode (如 'JG1000')，后续作为组织权限基础
  title             TEXT,
  tags              TEXT[],                                     -- 上游 tags[]
  mongo_doc         JSONB,                                      -- 完整 MongoDB ResearchReportRecord 文档（取代旧的 api_metadata）
  parse_status      TEXT,                                       -- upstream parseStatus: 'completed' | 'pending' | ...
  triage_decision   TEXT        NOT NULL DEFAULT 'pending',     -- 'pending' | 'pass' | 'commit' | 'brief'
  ingested_page_id  BIGINT,
  ingested_at       TIMESTAMPTZ,
  skipped_at        TIMESTAMPTZ,
  skip_reason       TEXT,
  -- 标准审计字段
  extend            JSONB,
  create_by         VARCHAR(64) NOT NULL DEFAULT '',
  update_by         VARCHAR(64) NOT NULL DEFAULT '',
  create_time       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted           SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.11 raw_data — JSONB sidecar
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_data (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id     BIGINT      NOT NULL,
  source      TEXT        NOT NULL,                             -- 'mineru_content_list' | 'aecapllc_api' | ...
  data        JSONB       NOT NULL,
  fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- 标准审计字段
  extend      JSONB,
  create_by   VARCHAR(64) NOT NULL DEFAULT '',
  update_by   VARCHAR(64) NOT NULL DEFAULT '',
  create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted     SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.12 page_versions — 快照历史
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS page_versions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id       BIGINT      NOT NULL,
  content       TEXT        NOT NULL,
  timeline      TEXT        NOT NULL DEFAULT '',
  frontmatter   JSONB       NOT NULL DEFAULT '{}',
  edited_by     TEXT,                                           -- 'agent:claude' | 'human:levin' | 'system:auto'
  reason        TEXT,                                           -- 'ingest' | 'manual edit' | 'enrich'
  snapshot_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- 标准审计字段
  extend        JSONB,
  create_by     VARCHAR(64) NOT NULL DEFAULT '',
  update_by     VARCHAR(64) NOT NULL DEFAULT '',
  create_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted       SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.13 events — 审计 log（结构化版的 wiki/log.md）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor       TEXT        NOT NULL,                             -- 'agent:claude' | 'human:levin' | 'system:cron'
  action      TEXT        NOT NULL,                             -- 'ingest' | 'create_page' | 'update_fact' | ...
  entity_type TEXT,
  entity_id   BIGINT,
  payload     JSONB,
  -- 标准审计字段
  extend      JSONB,
  create_by   VARCHAR(64) NOT NULL DEFAULT '',
  update_by   VARCHAR(64) NOT NULL DEFAULT '',
  create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted     SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.14 minion_jobs — Postgres 原生异步队列
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS minion_jobs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT        NOT NULL,                            -- 'embed_chunks' | 'extract_facts' | 'enrich_entity' | 'detect_signals'
  status       TEXT        NOT NULL DEFAULT 'waiting',          -- 'waiting' | 'active' | 'completed' | 'failed'
  data         JSONB       NOT NULL,
  attempts     INTEGER     NOT NULL DEFAULT 0,
  max_attempts INTEGER     NOT NULL DEFAULT 3,
  result       JSONB,
  error        TEXT,
  started_at   TIMESTAMPTZ,
  finished_at  TIMESTAMPTZ,
  -- 标准审计字段
  extend       JSONB,
  create_by    VARCHAR(64) NOT NULL DEFAULT '',
  update_by    VARCHAR(64) NOT NULL DEFAULT '',
  create_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted      SMALLINT    NOT NULL DEFAULT 0
);


-- -----------------------------------------------------------------------------
-- 2.15 config — 配置 KV
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS config (
  id          TEXT PRIMARY KEY,                                 -- 配置 key（如 'embedding_model'），同时作为主键
  value       TEXT        NOT NULL,
  -- 标准审计字段
  extend      JSONB,
  create_by   VARCHAR(64) NOT NULL DEFAULT '',
  update_by   VARCHAR(64) NOT NULL DEFAULT '',
  create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted     SMALLINT    NOT NULL DEFAULT 0
);


-- =============================================================================
-- §3. 索引
-- =============================================================================
--
-- 设计原则：所有"自然唯一性"约束改为 partial unique index WHERE deleted = 0。
-- 软删除一行后允许重建相同 key 的新行，避免"灵魂占位"问题。
-- 应用层 ON CONFLICT (col) 仍然能命中（PG 支持 partial 索引作为 conflict target，
-- 前提是 INSERT 行满足索引谓词，本仓所有 INSERT 都默认 deleted=0，自然满足）。
-- =============================================================================

-- 3.0 sources（原 UNIQUE name）
CREATE UNIQUE INDEX IF NOT EXISTS uq_sources_name
  ON sources (name) WHERE deleted = 0;

-- 3.1 pages
CREATE UNIQUE INDEX IF NOT EXISTS uq_pages_source_slug
  ON pages (source_id, slug) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_pages_type        ON pages (type);
CREATE INDEX IF NOT EXISTS idx_pages_ticker      ON pages (ticker) WHERE ticker IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pages_aliases     ON pages USING GIN (aliases);
CREATE INDEX IF NOT EXISTS idx_pages_frontmatter ON pages USING GIN (frontmatter);
CREATE INDEX IF NOT EXISTS idx_pages_sector      ON pages (sector) WHERE sector IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pages_tsv         ON pages USING GIN (tsv);
CREATE INDEX IF NOT EXISTS idx_pages_embedding   ON pages USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_pages_updated     ON pages (update_time DESC);
CREATE INDEX IF NOT EXISTS idx_pages_title_trgm  ON pages USING GIN (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_pages_active      ON pages (type, update_time DESC) WHERE deleted = 0 AND status = 'active';
CREATE INDEX IF NOT EXISTS idx_pages_org         ON pages (org_code) WHERE org_code IS NOT NULL;

-- 3.2 content_chunks
CREATE UNIQUE INDEX IF NOT EXISTS uq_chunks_page_index
  ON content_chunks (page_id, chunk_index) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_chunks_page       ON content_chunks (page_id);
CREATE INDEX IF NOT EXISTS idx_chunks_embedding  ON content_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_chunks_type       ON content_chunks (chunk_type);

-- 3.3 links
CREATE UNIQUE INDEX IF NOT EXISTS uq_links
  ON links (from_page_id, to_page_id, link_type, link_source, origin_page_id)
  NULLS NOT DISTINCT
  WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_links_from        ON links (from_page_id);
CREATE INDEX IF NOT EXISTS idx_links_to          ON links (to_page_id);
CREATE INDEX IF NOT EXISTS idx_links_type        ON links (link_type);
CREATE INDEX IF NOT EXISTS idx_links_source      ON links (link_source);

-- 3.4 tags
CREATE UNIQUE INDEX IF NOT EXISTS uq_tags_page_tag
  ON tags (page_id, tag) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_tags_tag          ON tags (tag);
CREATE INDEX IF NOT EXISTS idx_tags_page         ON tags (page_id);

-- 3.5 facts
CREATE INDEX IF NOT EXISTS idx_facts_entity_metric  ON facts (entity_page_id, metric);
CREATE INDEX IF NOT EXISTS idx_facts_metric_current ON facts (metric, valid_to) WHERE valid_to IS NULL;
CREATE INDEX IF NOT EXISTS idx_facts_period         ON facts (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_facts_source         ON facts (source_page_id);

-- 3.6 theses
CREATE INDEX IF NOT EXISTS idx_theses_status     ON theses (status) WHERE status IN ('active', 'monitoring');
CREATE INDEX IF NOT EXISTS idx_theses_target     ON theses (target_page_id);
CREATE INDEX IF NOT EXISTS idx_theses_direction  ON theses (direction);

-- 3.7 signals
CREATE INDEX IF NOT EXISTS idx_signals_unresolved ON signals (detected_at DESC) WHERE NOT resolved;
CREATE INDEX IF NOT EXISTS idx_signals_entity     ON signals (entity_page_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_thesis     ON signals (thesis_page_id) WHERE thesis_page_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_signals_severity   ON signals (severity, detected_at DESC) WHERE NOT resolved;

-- 3.8 timeline_entries
CREATE INDEX IF NOT EXISTS idx_timeline_entity_date ON timeline_entries (entity_page_id, event_date DESC);
CREATE INDEX IF NOT EXISTS idx_timeline_event_type  ON timeline_entries (event_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_timeline_dedup
  ON timeline_entries (entity_page_id, event_date, summary)
  NULLS NOT DISTINCT
  WHERE deleted = 0;

-- 3.9 raw_files
CREATE UNIQUE INDEX IF NOT EXISTS uq_raw_files_research_id
  ON raw_files (research_id) WHERE deleted = 0 AND research_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_raw_files_pending       ON raw_files (create_time DESC) WHERE triage_decision = 'pending' AND ingested_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_raw_files_research_type ON raw_files (research_type);
CREATE INDEX IF NOT EXISTS idx_raw_files_triage_decision ON raw_files (triage_decision);
CREATE INDEX IF NOT EXISTS idx_raw_files_org           ON raw_files (org_code) WHERE org_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_raw_files_tags          ON raw_files USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_raw_files_skipped       ON raw_files (skipped_at) WHERE skipped_at IS NOT NULL;

-- 3.10 raw_data
CREATE UNIQUE INDEX IF NOT EXISTS uq_raw_data_page_source
  ON raw_data (page_id, source) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_raw_data_page     ON raw_data (page_id);

-- 3.11 page_versions
CREATE INDEX IF NOT EXISTS idx_versions_page     ON page_versions (page_id, snapshot_at DESC);

-- 3.12 events
CREATE INDEX IF NOT EXISTS idx_events_ts         ON events (ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_actor_ts   ON events (actor, ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_action     ON events (action, ts DESC);

-- 3.13 minion_jobs
CREATE INDEX IF NOT EXISTS idx_jobs_pending      ON minion_jobs (name, create_time) WHERE status = 'waiting';
CREATE INDEX IF NOT EXISTS idx_jobs_status       ON minion_jobs (status, create_time DESC);


-- =============================================================================
-- §4. Triggers
-- =============================================================================

-- 4.1 pages.tsv 自动维护（全文索引）
-- aliases 与 title 同权重 A——别名（"腾讯"、"700.HK"、"Tencent"）就是替代标题
-- tokens_zh 优先于 content：应用层用 jieba 切完的空格分隔串
CREATE OR REPLACE FUNCTION update_pages_tsv() RETURNS trigger AS $$
BEGIN
  NEW.tsv :=
    setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(NEW.aliases, ' '), '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.tokens_zh, NEW.content, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW.timeline, '')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pages_tsv ON pages;
CREATE TRIGGER trg_pages_tsv
  BEFORE INSERT OR UPDATE ON pages
  FOR EACH ROW EXECUTE FUNCTION update_pages_tsv();


-- 4.2 update_time 由应用层维护（每次 UPDATE 显式 SET update_time = NOW()），
--     不在 DB 层做 trigger，便于事务可控、批处理友好。


-- =============================================================================
-- §5. 种子数据
-- =============================================================================

-- 5.1 默认 source（多租户的"main wiki"分区）
INSERT INTO sources (id, name, description, create_by) VALUES
  ('default', '主投资研究 wiki', '默认 wiki 分区', 'system:init')
ON CONFLICT (id) DO NOTHING;


-- 5.2 系统配置
INSERT INTO config (id, value, create_by) VALUES
  ('schema_version',                       '2',                       'system:init'),
  ('embedding_model',                      'text-embedding-3-large',  'system:init'),
  ('embedding_dimensions',                 '1536',                    'system:init'),
  ('chunk_strategy',                       'mineru-aware',            'system:init'),
  ('default_locale',                       'zh-CN',                   'system:init'),
  -- Fact 抽取（默认三层全开）
  ('fact_extract_tier_a_enabled',          'true',                    'system:init'),
  ('fact_extract_tier_b_enabled',          'true',                    'system:init'),
  ('fact_extract_tier_c_enabled',          'true',                    'system:init'),
  ('fact_extract_llm_model',               'claude-haiku-4-5',        'system:init'),
  ('fact_extract_llm_max_cost_per_page',   '0.10',                    'system:init'),
  ('fact_extract_pct_auto_convert',        'true',                    'system:init'),
  ('fact_extract_outlier_zscore_threshold','3.0',                     'system:init')
ON CONFLICT (id) DO NOTHING;


-- =============================================================================
-- §6. 部署完成提示
-- =============================================================================

DO $$
DECLARE
  n_tables  INTEGER;
  n_indexes INTEGER;
BEGIN
  SELECT count(*) INTO n_tables  FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE';
  SELECT count(*) INTO n_indexes FROM pg_indexes
    WHERE schemaname = 'public';
  RAISE NOTICE '';
  RAISE NOTICE '=============================================================';
  RAISE NOTICE 'LLM Wiki v2 schema 部署完成';
  RAISE NOTICE '  Tables  : % (期望 15)', n_tables;
  RAISE NOTICE '  Indexes : %', n_indexes;
  RAISE NOTICE '  Triggers: pages.tsv 自动维护（update_time 由应用层维护）';
  RAISE NOTICE '  Seed    : sources.default + config 5 项';
  RAISE NOTICE '=============================================================';
END$$;
