BEGIN;

-- v2.6.0 — durable agent runtime
-- 1. minion_jobs 增加 progress，用于 agent worker 心跳/步骤跟踪
ALTER TABLE minion_jobs
  ADD COLUMN IF NOT EXISTS progress JSONB;

-- 2. agent_messages：持久化每轮 user/assistant message
CREATE TABLE IF NOT EXISTS agent_messages (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id       BIGINT      NOT NULL,
  turn_index   INTEGER     NOT NULL,
  role         TEXT        NOT NULL,
  content      JSONB       NOT NULL,
  model        TEXT,
  stop_reason  TEXT,
  tokens_in    INTEGER,
  tokens_out   INTEGER,
  started_at   TIMESTAMPTZ,
  finished_at  TIMESTAMPTZ,
  metadata     JSONB       NOT NULL DEFAULT '{}'::jsonb,
  extend       JSONB,
  create_by    VARCHAR(64) NOT NULL DEFAULT '',
  update_by    VARCHAR(64) NOT NULL DEFAULT '',
  create_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted      SMALLINT    NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_messages_job_turn
  ON agent_messages (job_id, turn_index) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_agent_messages_job_turn
  ON agent_messages (job_id, turn_index);

-- 3. agent_tool_executions：持久化 tool_use / tool_result
CREATE TABLE IF NOT EXISTS agent_tool_executions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id       BIGINT      NOT NULL,
  turn_index   INTEGER     NOT NULL,
  tool_use_id  TEXT        NOT NULL,
  tool_name    TEXT        NOT NULL,
  status       TEXT        NOT NULL DEFAULT 'pending',
  input        JSONB       NOT NULL DEFAULT '{}'::jsonb,
  output       JSONB,
  error        TEXT,
  started_at   TIMESTAMPTZ,
  finished_at  TIMESTAMPTZ,
  metadata     JSONB       NOT NULL DEFAULT '{}'::jsonb,
  extend       JSONB,
  create_by    VARCHAR(64) NOT NULL DEFAULT '',
  update_by    VARCHAR(64) NOT NULL DEFAULT '',
  create_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted      SMALLINT    NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_tool_exec_job_tool_use
  ON agent_tool_executions (job_id, tool_use_id) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_agent_tool_exec_job_turn
  ON agent_tool_executions (job_id, turn_index);
CREATE INDEX IF NOT EXISTS idx_agent_tool_exec_status
  ON agent_tool_executions (status, started_at DESC);

-- 4. agent_run 快速查 skill 名
CREATE INDEX IF NOT EXISTS idx_jobs_agent_skill
  ON minion_jobs ((data->>'skill')) WHERE name = 'agent_run';

COMMIT;
