BEGIN;

-- v2.7.0 — llm_usage 通用 token 用量表
-- 统一记录所有 OpenAI 调用：embedding / agent runtime / web chat / fact extract /
-- chunker llm / query expansion。
-- 与 agent_messages.tokens_in/out 并行写入（agent_messages 是会话历史，本表是计量）。

CREATE TABLE IF NOT EXISTS llm_usage (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source          TEXT     NOT NULL,
  model           TEXT     NOT NULL,
  tokens_in       INTEGER,
  tokens_out      INTEGER,
  total_tokens    INTEGER,
  request_count   INTEGER  NOT NULL DEFAULT 1,
  job_id          BIGINT,
  metadata        JSONB    NOT NULL DEFAULT '{}'::jsonb,
  extend          JSONB,
  create_by       VARCHAR(64) NOT NULL DEFAULT '',
  update_by       VARCHAR(64) NOT NULL DEFAULT '',
  create_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted         SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_llm_usage_create_time
  ON llm_usage (create_time DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_llm_usage_source_time
  ON llm_usage (source, create_time DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_llm_usage_model_time
  ON llm_usage (model, create_time DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_llm_usage_job
  ON llm_usage (job_id) WHERE deleted = 0 AND job_id IS NOT NULL;

COMMIT;
