BEGIN;

-- v2.7.10 — page_comments：用户在 web UI 上对 page 留下的评论
-- 用途：人工反馈通道，agent / skill 后续可以读这些评论调整生成策略。
-- 没有用户系统，author 为 free-text 自填。parent_id 留作未来 reply 扩展。

CREATE TABLE IF NOT EXISTS page_comments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id     BIGINT      NOT NULL,
  author      TEXT        NOT NULL,
  content     TEXT        NOT NULL,
  parent_id   BIGINT,
  metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb,
  extend      JSONB,
  create_by   VARCHAR(64) NOT NULL DEFAULT '',
  update_by   VARCHAR(64) NOT NULL DEFAULT '',
  create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted     SMALLINT    NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_page_comments_page
  ON page_comments (page_id, create_time DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_page_comments_create_time
  ON page_comments (create_time DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_page_comments_parent
  ON page_comments (parent_id) WHERE deleted = 0 AND parent_id IS NOT NULL;

COMMIT;
