-- v2.8.1 — schedules table
--
-- Database-native orchestration layer. Worker polls due schedules and enqueues
-- minion_jobs atomically, so external cron is no longer required for wiki upkeep.

CREATE TABLE IF NOT EXISTS schedules (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             TEXT        NOT NULL,
  status           TEXT        NOT NULL DEFAULT 'active',
  job_name         TEXT        NOT NULL,
  job_data         JSONB       NOT NULL DEFAULT '{}'::jsonb,
  priority         INTEGER     NOT NULL DEFAULT 50,
  max_attempts     INTEGER     NOT NULL DEFAULT 3,
  next_run_at      TIMESTAMPTZ,
  interval_seconds INTEGER,
  max_runs         INTEGER,
  run_count        INTEGER     NOT NULL DEFAULT 0,
  last_run_at      TIMESTAMPTZ,
  last_job_id      BIGINT,
  last_error       TEXT,
  extend           JSONB,
  create_by        VARCHAR(64) NOT NULL DEFAULT '',
  update_by        VARCHAR(64) NOT NULL DEFAULT '',
  create_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted          SMALLINT    NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_schedules_name
  ON schedules (name) WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_schedules_due
  ON schedules (status, next_run_at) WHERE deleted = 0 AND status = 'active';

CREATE INDEX IF NOT EXISTS idx_schedules_job_name
  ON schedules (job_name);

INSERT INTO events (actor, action, entity_type, payload, create_by, update_by)
VALUES (
  'system:init',
  'schema_migration',
  'migration',
  '{"migration":"v2.8.1-schedules"}'::jsonb,
  'system:init',
  'system:init'
);
