-- v2.8.2 — entity candidate queue for mention-first / promote-later graph governance.

CREATE TABLE IF NOT EXISTS entity_candidates (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id           TEXT        NOT NULL DEFAULT 'default',
  proposed_slug       TEXT        NOT NULL,
  proposed_type       TEXT        NOT NULL,
  display_name        TEXT,
  aliases             TEXT[],
  status              TEXT        NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'promoted', 'merged', 'rejected')),
  evidence_count      INTEGER     NOT NULL DEFAULT 0,
  source_page_ids     BIGINT[]    NOT NULL DEFAULT ARRAY[]::BIGINT[],
  last_source_page_id BIGINT,
  suggestions         JSONB       NOT NULL DEFAULT '[]'::jsonb,
  promoted_page_id    BIGINT,
  merged_into_page_id BIGINT,
  reject_reason       TEXT,
  resolved_at         TIMESTAMPTZ,
  first_seen_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata            JSONB       NOT NULL DEFAULT '{}'::jsonb,
  extend              JSONB,
  create_by           VARCHAR(64) NOT NULL DEFAULT '',
  update_by           VARCHAR(64) NOT NULL DEFAULT '',
  create_time         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  update_time         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted             SMALLINT    NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_entity_candidates_source_slug
  ON entity_candidates (source_id, proposed_slug) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_entity_candidates_status
  ON entity_candidates (status, last_seen_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_entity_candidates_type
  ON entity_candidates (proposed_type, status) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_entity_candidates_source_page_ids
  ON entity_candidates USING GIN (source_page_ids) WHERE deleted = 0;
